#!/bin/sh

SSHVARS="SSH_CLIENT SSH_TTY SSH_AUTH_SOCK SSH_CONNECTION DISPLAY"

for var in ${SSHVARS} ; do
    (eval echo $var=\$$var) | sed  's/=/="/
                                    s/$/"/
                                    s/^/export /'
done 1>$HOME/bin/fixssh
